FROM tomcat:9-jre17-temurin-focal
MAINTAINER "FIZ-Karlsruhe"

ARG UNAME=oai_backend
ARG UID=8007
ARG GID=8007

RUN groupadd -g $GID -o $UNAME
RUN useradd -m -u $UID -g $GID -o -s /bin/bash $UNAME
RUN chown -R ${UNAME}:${UNAME} /usr/local/tomcat/
RUN chmod -R 770 /usr/local/tomcat/

#Install + Configure Cron
COPY docker/oai_backend_init.sh /usr/local/bin/oai_backend_init.sh
RUN chmod +x /usr/local/bin/oai_backend_init.sh
RUN /usr/local/bin/oai_backend_init.sh

USER $UNAME
COPY target/oai-backend.war /usr/local/tomcat/webapps
